server:
  port: 8000
eureka:
  instance:
    prefer-ip-address: true
  server:
    # 关闭保护模式
    enable-self-preservation: false
    # 清理间隔（默认是60 * 1000 毫秒）
    eviction-interval-timer-in-ms: 60000
    # Eureka 拉取服务列表时间（默认：30秒）
    remote-region-registry-fetch-interval: 5
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
      # 从 Eureka 服务器端获取注册信息的间隔时间（默认：30秒）
    registry-fetch-interval-seconds: 5
spring:
  application:
    name: spring-cloud-eureka-server