eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/marcodeba/spring-cloud-config-server.git
          username: marcodeba@aliyun.com
          password: marcofuckyou1234
  application:
    name: spring-cloud-config-server
